{
 "title": "Bitbucket",
 "description": "Dashboard for JVM metrics with Prometheus / JMX Exporter",
 "tags": [
  "JVM",
  "git",
  "Bitbucket",
  "Atlassian"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "30s",
 "panels": [
  { "title": "License", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Maintance Expiry",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bitbucket_maintenance_expiry_days_gauge{job=\"git\"}"
    }
   ]
  },
  {
   "title": "Current Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bitbucket_all_users_gauge{job=\"git\"}"
    }
   ]
  },
  {
   "title": "Aloowed Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 8, "x": 16, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bitbucket_active_users_gauge{job=\"git\"}"
    }
   ]
  },
  { "title": "Events", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 } },
  {
   "title": "Pushes today by project",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(bitbucket_repo_push_count) by (project)",
     "legendFormat": "{{project}}"
    }
   ]
  },
  {
   "title": "Pishes today by username",
   "type": "graph",
   "gridPos": { "h": 9, "w": 7, "x": 8, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "count(bitbucket_repo_push_count) by (username)",
     "legendFormat": "{{username}}"
    }
   ]
  },
  {
   "title": "Pull Requests",
   "type": "graph",
   "gridPos": { "h": 9, "w": 8, "x": 15, "y": 6 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "bitbucket_pull_request_open", "legendFormat": "opened" },
    { "expr": "bitbucket_pull_request_merge", "legendFormat": "merged" },
    { "expr": "bitbucket_pull_request_decline", "legendFormat": "decline" }
   ]
  },
  { "title": "JVM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Memory used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_memory_bytes_used{job=\"git\"}",
     "legendFormat": "{{area}} memory"
    }
   ]
  },
  {
   "title": "Threads used",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_threads_current{job=\"git\"}",
     "legendFormat": "current"
    },
    {
     "expr": "jvm_threads_daemon{job=\"git\"}",
     "legendFormat": "daemon"
    }
   ]
  },
  {
   "title": "GC time / 1 min. rate",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "rate(jvm_gc_collection_seconds_sum{job=\"git\"}[1m])",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  {
   "title": "GC count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "jvm_gc_collection_seconds_count{job=\"git\"}",
     "legendFormat": "{{gc}}"
    }
   ]
  },
  { "title": "Common Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 23 } },
  {
   "title": "Total Projects",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 0, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    { "expr": "bitbucket_total_projects_gauge" }
   ]
  },
  {
   "title": "Repositories",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 5, "x": 6, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bitbucket_total_repositories_gauge"
    }
   ]
  },
  {
   "title": "Opened Pull Requests",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 24 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "bitbucket_total_pull_requests_gauge"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "singlestat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 24 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "expr": "process_start_time_seconds{job=\"git\"}"
    }
   ]
  }
 ]
}